// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWckvfUEksOlI8rherjk4i59PEvVT92rw',
    appId: '1:794826948632:android:86d6c0825a4db537c7436d',
    messagingSenderId: '794826948632',
    projectId: 'real-time-database-65dc5',
    databaseURL:
        'https://real-time-database-65dc5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-database-65dc5.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0C5yiFfsQsdb9NbdSDHxE6BCmEqUYl0Q',
    appId: '1:794826948632:web:0be01e556cf5f8a3c7436d',
    messagingSenderId: '794826948632',
    projectId: 'real-time-database-65dc5',
    authDomain: 'real-time-database-65dc5.firebaseapp.com',
    databaseURL:
        'https://real-time-database-65dc5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-database-65dc5.firebasestorage.app',
    measurementId: 'G-YGXSMJR3J3',
  );
}
